package service_test

import (
	"reflect"
	"testing"

	"github.com/Apricot-S/mjai-manue-go/internal/domain/game/player"
	"github.com/Apricot-S/mjai-manue-go/internal/domain/game/player/hand"
	"github.com/Apricot-S/mjai-manue-go/internal/domain/game/player/meld"
	"github.com/Apricot-S/mjai-manue-go/internal/domain/game/service"
	"github.com/Apricot-S/mjai-manue-go/internal/domain/game/service/block"
	"github.com/Apricot-S/mjai-manue-go/internal/domain/game/tile"
	"github.com/Apricot-S/mjai-manue-go/internal/domain/game/wind"
)

func TestCalculateFuHan(t *testing.T) {
	tests := []struct {
		name           string
		handCodes      []string
		handBlocks     []block.Block
		melds          []meld.Meld
		prevalentWind  wind.Wind
		seatWind       wind.Wind
		doraIndicators []tile.Tile
		riichi         bool
		wantFu         int
		wantHan        int
		wantYakus      map[string]int
	}{
		{
			name:      "no Yaku",
			handCodes: []string{"1m", "1m", "1m", "2p", "3p", "4p", "3s", "4s", "5sr", "6s", "6s", "6s", "9s", "9s"},
			handBlocks: []block.Block{
				block.MustTriplet(*tile.MustTileFromCode("1m")),
				block.MustSequence(*tile.MustTileFromCode("2p")),
				block.MustSequence(*tile.MustTileFromCode("3s")),
				block.MustTriplet(*tile.MustTileFromCode("6s")),
				block.MustPair(*tile.MustTileFromCode("9s")),
			},
			melds:          nil,
			prevalentWind:  wind.East,
			seatWind:       wind.South,
			doraIndicators: []tile.Tile{*tile.MustTileFromCode("1p")},
			riichi:         false,
			wantFu:         40,
			wantHan:        0,
			wantYakus:      map[string]int{},
		},
		{
			name:      "only Riichi",
			handCodes: []string{"1m", "1m", "1m", "2p", "3p", "4p", "3s", "4s", "5s", "6s", "6s", "6s", "9s", "9s"},
			handBlocks: []block.Block{
				block.MustTriplet(*tile.MustTileFromCode("1m")),
				block.MustSequence(*tile.MustTileFromCode("2p")),
				block.MustSequence(*tile.MustTileFromCode("3s")),
				block.MustTriplet(*tile.MustTileFromCode("6s")),
				block.MustPair(*tile.MustTileFromCode("9s")),
			},
			melds:          nil,
			prevalentWind:  wind.East,
			seatWind:       wind.South,
			doraIndicators: []tile.Tile{*tile.MustTileFromCode("9s")},
			riichi:         true,
			wantFu:         40,
			wantHan:        1,
			wantYakus:      map[string]int{"reach": 1},
		},
		{
			name:      "only Tanyao",
			handCodes: []string{"2m", "2m", "2m", "2p", "3p", "4p", "3s", "4s", "5s", "6s", "6s", "6s", "8s", "8s"},
			handBlocks: []block.Block{
				block.MustTriplet(*tile.MustTileFromCode("2m")),
				block.MustSequence(*tile.MustTileFromCode("2p")),
				block.MustSequence(*tile.MustTileFromCode("3s")),
				block.MustTriplet(*tile.MustTileFromCode("6s")),
				block.MustPair(*tile.MustTileFromCode("8s")),
			},
			melds:          nil,
			prevalentWind:  wind.East,
			seatWind:       wind.South,
			doraIndicators: nil,
			riichi:         false,
			wantFu:         40,
			wantHan:        1,
			wantYakus:      map[string]int{"tyc": 1},
		},
		{
			name:      "Riichi Tanyao",
			handCodes: []string{"2m", "2m", "2m", "2p", "3p", "4p", "3s", "4s", "5s", "6s", "6s", "6s", "8s", "8s"},
			handBlocks: []block.Block{
				block.MustTriplet(*tile.MustTileFromCode("2m")),
				block.MustSequence(*tile.MustTileFromCode("2p")),
				block.MustSequence(*tile.MustTileFromCode("3s")),
				block.MustTriplet(*tile.MustTileFromCode("6s")),
				block.MustPair(*tile.MustTileFromCode("8s")),
			},
			melds:          nil,
			prevalentWind:  wind.East,
			seatWind:       wind.South,
			doraIndicators: nil,
			riichi:         true,
			wantFu:         40,
			wantHan:        2,
			wantYakus:      map[string]int{"reach": 1, "tyc": 1},
		},
		{
			name:      "only Chantaiyao concealed",
			handCodes: []string{"1m", "1m", "1m", "1p", "2p", "3p", "1s", "2s", "3s", "9s", "9s", "9s", "N", "N"},
			handBlocks: []block.Block{
				block.MustTriplet(*tile.MustTileFromCode("1m")),
				block.MustSequence(*tile.MustTileFromCode("1p")),
				block.MustSequence(*tile.MustTileFromCode("1s")),
				block.MustTriplet(*tile.MustTileFromCode("9s")),
				block.MustPair(*tile.MustTileFromCode("N")),
			},
			melds:          nil,
			prevalentWind:  wind.East,
			seatWind:       wind.South,
			doraIndicators: nil,
			riichi:         false,
			wantFu:         40,
			wantHan:        2,
			wantYakus:      map[string]int{"cty": 2},
		},
		{
			name:      "only Chantaiyao open",
			handCodes: []string{"1p", "2p", "3p", "9s", "9s", "9s", "N", "N"},
			handBlocks: []block.Block{
				block.MustSequence(*tile.MustTileFromCode("1p")),
				block.MustTriplet(*tile.MustTileFromCode("9s")),
				block.MustPair(*tile.MustTileFromCode("N")),
			},
			melds: []meld.Meld{
				meld.MustPon(
					*tile.MustTileFromCode("1m"),
					[2]tile.Tile{*tile.MustTileFromCode("1m"), *tile.MustTileFromCode("1m")},
					*player.MustID(2),
				),
				meld.MustChii(
					*tile.MustTileFromCode("7s"),
					[2]tile.Tile{*tile.MustTileFromCode("8s"), *tile.MustTileFromCode("9s")},
					*player.MustID(2),
				),
			},
			prevalentWind:  wind.East,
			seatWind:       wind.South,
			doraIndicators: nil,
			riichi:         false,
			wantFu:         30,
			wantHan:        1,
			wantYakus:      map[string]int{"cty": 1},
		},
		{
			name:      "only Pinfu",
			handCodes: []string{"1m", "2m", "3m", "2p", "3p", "4p", "3s", "4s", "5s", "6s", "7s", "8s", "W", "W"},
			handBlocks: []block.Block{
				block.MustSequence(*tile.MustTileFromCode("1m")),
				block.MustSequence(*tile.MustTileFromCode("2p")),
				block.MustSequence(*tile.MustTileFromCode("3s")),
				block.MustSequence(*tile.MustTileFromCode("6s")),
				block.MustPair(*tile.MustTileFromCode("W")),
			},
			melds:          nil,
			prevalentWind:  wind.East,
			seatWind:       wind.South,
			doraIndicators: nil,
			riichi:         false,
			wantFu:         30,
			wantHan:        1,
			wantYakus:      map[string]int{"pf": 1},
		},
		{
			name:      "not Pinfu: prevalentWind",
			handCodes: []string{"1m", "2m", "3m", "2p", "3p", "4p", "3s", "4s", "5s", "6s", "7s", "8s", "E", "E"},
			handBlocks: []block.Block{
				block.MustSequence(*tile.MustTileFromCode("1m")),
				block.MustSequence(*tile.MustTileFromCode("2p")),
				block.MustSequence(*tile.MustTileFromCode("3s")),
				block.MustSequence(*tile.MustTileFromCode("6s")),
				block.MustPair(*tile.MustTileFromCode("E")),
			},
			melds:          nil,
			prevalentWind:  wind.East,
			seatWind:       wind.South,
			doraIndicators: nil,
			riichi:         false,
			wantFu:         40,
			wantHan:        0,
			wantYakus:      map[string]int{},
		},
		{
			name:      "not Pinfu: seatWind",
			handCodes: []string{"1m", "2m", "3m", "2p", "3p", "4p", "3s", "4s", "5s", "6s", "7s", "8s", "S", "S"},
			handBlocks: []block.Block{
				block.MustSequence(*tile.MustTileFromCode("1m")),
				block.MustSequence(*tile.MustTileFromCode("2p")),
				block.MustSequence(*tile.MustTileFromCode("3s")),
				block.MustSequence(*tile.MustTileFromCode("6s")),
				block.MustPair(*tile.MustTileFromCode("S")),
			},
			melds:          nil,
			prevalentWind:  wind.East,
			seatWind:       wind.South,
			doraIndicators: nil,
			riichi:         false,
			wantFu:         40,
			wantHan:        0,
			wantYakus:      map[string]int{},
		},
		{
			name:      "not Pinfu: dragons",
			handCodes: []string{"1m", "2m", "3m", "2p", "3p", "4p", "3s", "4s", "5s", "6s", "7s", "8s", "P", "P"},
			handBlocks: []block.Block{
				block.MustSequence(*tile.MustTileFromCode("1m")),
				block.MustSequence(*tile.MustTileFromCode("2p")),
				block.MustSequence(*tile.MustTileFromCode("3s")),
				block.MustSequence(*tile.MustTileFromCode("6s")),
				block.MustPair(*tile.MustTileFromCode("P")),
			},
			melds:          nil,
			prevalentWind:  wind.East,
			seatWind:       wind.South,
			doraIndicators: nil,
			riichi:         false,
			wantFu:         40,
			wantHan:        0,
			wantYakus:      map[string]int{},
		},
		{
			name:      "only Dragons",
			handCodes: []string{"1p", "2p", "3p", "8s", "8s", "8s", "E", "E"},
			handBlocks: []block.Block{
				block.MustSequence(*tile.MustTileFromCode("1p")),
				block.MustTriplet(*tile.MustTileFromCode("8s")),
				block.MustPair(*tile.MustTileFromCode("E")),
			},
			melds: []meld.Meld{
				meld.MustPon(
					*tile.MustTileFromCode("F"),
					[2]tile.Tile{*tile.MustTileFromCode("F"), *tile.MustTileFromCode("F")},
					*player.MustID(2),
				),
				meld.MustPon(
					*tile.MustTileFromCode("N"),
					[2]tile.Tile{*tile.MustTileFromCode("N"), *tile.MustTileFromCode("N")},
					*player.MustID(2),
				),
			},
			prevalentWind:  wind.East,
			seatWind:       wind.South,
			doraIndicators: nil,
			riichi:         false,
			wantFu:         30,
			wantHan:        1,
			wantYakus:      map[string]int{"ykh": 1},
		},
		{
			name:      "only prevalentWind",
			handCodes: []string{"1p", "2p", "3p", "8s", "8s", "8s", "N", "N"},
			handBlocks: []block.Block{
				block.MustSequence(*tile.MustTileFromCode("1p")),
				block.MustTriplet(*tile.MustTileFromCode("8s")),
				block.MustPair(*tile.MustTileFromCode("N")),
			},
			melds: []meld.Meld{
				meld.MustPon(
					*tile.MustTileFromCode("1m"),
					[2]tile.Tile{*tile.MustTileFromCode("1m"), *tile.MustTileFromCode("1m")},
					*player.MustID(2),
				),
				meld.MustPon(
					*tile.MustTileFromCode("E"),
					[2]tile.Tile{*tile.MustTileFromCode("E"), *tile.MustTileFromCode("E")},
					*player.MustID(2),
				),
			},
			prevalentWind:  wind.East,
			seatWind:       wind.South,
			doraIndicators: nil,
			riichi:         false,
			wantFu:         30,
			wantHan:        1,
			wantYakus:      map[string]int{"ykh": 1},
		},
		{
			name:      "only seatWind",
			handCodes: []string{"2p", "3p", "4p", "3s", "4s", "5s", "6s", "6s", "6s", "9s", "9s", "S", "S", "S"},
			handBlocks: []block.Block{
				block.MustSequence(*tile.MustTileFromCode("2p")),
				block.MustSequence(*tile.MustTileFromCode("3s")),
				block.MustTriplet(*tile.MustTileFromCode("6s")),
				block.MustPair(*tile.MustTileFromCode("9s")),
				block.MustTriplet(*tile.MustTileFromCode("S")),
			},
			melds:          nil,
			prevalentWind:  wind.East,
			seatWind:       wind.South,
			doraIndicators: nil,
			riichi:         false,
			wantFu:         40,
			wantHan:        1,
			wantYakus:      map[string]int{"ykh": 1},
		},
		{
			name:      "double wind and Dragons",
			handCodes: []string{"1p", "2p", "3p", "8s", "8s", "8s", "N", "N"},
			handBlocks: []block.Block{
				block.MustSequence(*tile.MustTileFromCode("1p")),
				block.MustTriplet(*tile.MustTileFromCode("8s")),
				block.MustPair(*tile.MustTileFromCode("N")),
			},
			melds: []meld.Meld{
				meld.MustPon(
					*tile.MustTileFromCode("E"),
					[2]tile.Tile{*tile.MustTileFromCode("E"), *tile.MustTileFromCode("E")},
					*player.MustID(2),
				),
				meld.MustCalledKan(
					*tile.MustTileFromCode("C"),
					[3]tile.Tile{*tile.MustTileFromCode("C"), *tile.MustTileFromCode("C"), *tile.MustTileFromCode("C")},
					*player.MustID(2),
				),
			},
			prevalentWind:  wind.East,
			seatWind:       wind.East,
			doraIndicators: nil,
			riichi:         false,
			wantFu:         30,
			wantHan:        3,
			wantYakus:      map[string]int{"ykh": 3},
		},
		{
			name:      "only Iipeikou",
			handCodes: []string{"1m", "1m", "1m", "2p", "3p", "4p", "3s", "4s", "5s", "3s", "4s", "5s", "9s", "9s"},
			handBlocks: []block.Block{
				block.MustTriplet(*tile.MustTileFromCode("1m")),
				block.MustSequence(*tile.MustTileFromCode("2p")),
				block.MustSequence(*tile.MustTileFromCode("3s")),
				block.MustSequence(*tile.MustTileFromCode("3s")),
				block.MustPair(*tile.MustTileFromCode("9s")),
			},
			melds:          nil,
			prevalentWind:  wind.East,
			seatWind:       wind.South,
			doraIndicators: nil,
			riichi:         false,
			wantFu:         40,
			wantHan:        1,
			wantYakus:      map[string]int{"ipk": 1},
		},
		{
			name:      "not Iipeikou: open",
			handCodes: []string{"2p", "3p", "4p", "3s", "4s", "5s", "3s", "4s", "5s", "9s", "9s"},
			handBlocks: []block.Block{
				block.MustSequence(*tile.MustTileFromCode("2p")),
				block.MustSequence(*tile.MustTileFromCode("3s")),
				block.MustSequence(*tile.MustTileFromCode("3s")),
				block.MustPair(*tile.MustTileFromCode("9s")),
			},
			melds: []meld.Meld{
				meld.MustPon(
					*tile.MustTileFromCode("1m"),
					[2]tile.Tile{*tile.MustTileFromCode("1m"), *tile.MustTileFromCode("1m")},
					*player.MustID(2),
				),
			},
			prevalentWind:  wind.East,
			seatWind:       wind.South,
			doraIndicators: nil,
			riichi:         false,
			wantFu:         30,
			wantHan:        0,
			wantYakus:      map[string]int{},
		},
		{
			name:      "only Sanshoku doujun concealed",
			handCodes: []string{"1m", "1m", "1m", "1m", "2m", "3m", "1p", "2p", "3p", "1s", "2s", "3s", "8s", "8s"},
			handBlocks: []block.Block{
				block.MustTriplet(*tile.MustTileFromCode("1m")),
				block.MustSequence(*tile.MustTileFromCode("1m")),
				block.MustSequence(*tile.MustTileFromCode("1p")),
				block.MustSequence(*tile.MustTileFromCode("1s")),
				block.MustPair(*tile.MustTileFromCode("8s")),
			},
			melds:          nil,
			prevalentWind:  wind.East,
			seatWind:       wind.South,
			doraIndicators: nil,
			riichi:         false,
			wantFu:         40,
			wantHan:        2,
			wantYakus:      map[string]int{"ssj": 2},
		},
		{
			name:      "only Sanshoku doujun open",
			handCodes: []string{"1m", "2m", "3m", "1p", "2p", "3p", "8s", "8s"},
			handBlocks: []block.Block{
				block.MustSequence(*tile.MustTileFromCode("1m")),
				block.MustSequence(*tile.MustTileFromCode("1p")),
				block.MustPair(*tile.MustTileFromCode("8s")),
			},
			melds: []meld.Meld{
				meld.MustPon(
					*tile.MustTileFromCode("1m"),
					[2]tile.Tile{*tile.MustTileFromCode("1m"), *tile.MustTileFromCode("1m")},
					*player.MustID(2),
				),
				meld.MustChii(
					*tile.MustTileFromCode("1s"),
					[2]tile.Tile{*tile.MustTileFromCode("2s"), *tile.MustTileFromCode("3s")},
					*player.MustID(2),
				),
			},
			prevalentWind:  wind.East,
			seatWind:       wind.South,
			doraIndicators: nil,
			riichi:         false,
			wantFu:         30,
			wantHan:        1,
			wantYakus:      map[string]int{"ssj": 1},
		},
		{
			name:      "only Ikki tsuukan concealed",
			handCodes: []string{"1m", "1m", "1m", "1p", "2p", "3p", "4p", "5p", "6p", "7p", "8p", "9p", "8s", "8s"},
			handBlocks: []block.Block{
				block.MustTriplet(*tile.MustTileFromCode("1m")),
				block.MustSequence(*tile.MustTileFromCode("1p")),
				block.MustSequence(*tile.MustTileFromCode("4p")),
				block.MustSequence(*tile.MustTileFromCode("7p")),
				block.MustPair(*tile.MustTileFromCode("8s")),
			},
			melds:          nil,
			prevalentWind:  wind.East,
			seatWind:       wind.South,
			doraIndicators: nil,
			riichi:         false,
			wantFu:         40,
			wantHan:        2,
			wantYakus:      map[string]int{"ikt": 2},
		},
		{
			name:      "only Ikki tsuukan open",
			handCodes: []string{"1m", "1m", "1m", "1p", "2p", "3p", "7p", "8p", "9p", "8s", "8s"},
			handBlocks: []block.Block{
				block.MustTriplet(*tile.MustTileFromCode("1m")),
				block.MustSequence(*tile.MustTileFromCode("1p")),
				block.MustSequence(*tile.MustTileFromCode("7p")),
				block.MustPair(*tile.MustTileFromCode("8s")),
			},
			melds: []meld.Meld{
				meld.MustChii(
					*tile.MustTileFromCode("4p"),
					[2]tile.Tile{*tile.MustTileFromCode("5p"), *tile.MustTileFromCode("6p")},
					*player.MustID(2),
				),
			},
			prevalentWind:  wind.East,
			seatWind:       wind.South,
			doraIndicators: nil,
			riichi:         false,
			wantFu:         30,
			wantHan:        1,
			wantYakus:      map[string]int{"ikt": 1},
		},
		{
			name:      "only Toitoihou",
			handCodes: []string{"2p", "2p", "2p", "6p", "6p", "N", "N", "N"},
			handBlocks: []block.Block{
				block.MustTriplet(*tile.MustTileFromCode("2p")),
				block.MustPair(*tile.MustTileFromCode("6p")),
				block.MustTriplet(*tile.MustTileFromCode("N")),
			},
			melds: []meld.Meld{
				meld.MustPon(
					*tile.MustTileFromCode("2m"),
					[2]tile.Tile{*tile.MustTileFromCode("2m"), *tile.MustTileFromCode("2m")},
					*player.MustID(2),
				),
				meld.MustCalledKan(
					*tile.MustTileFromCode("1m"),
					[3]tile.Tile{*tile.MustTileFromCode("1m"), *tile.MustTileFromCode("1m"), *tile.MustTileFromCode("1m")},
					*player.MustID(2),
				),
			},
			prevalentWind:  wind.East,
			seatWind:       wind.South,
			doraIndicators: nil,
			riichi:         false,
			wantFu:         30,
			wantHan:        2,
			wantYakus:      map[string]int{"tth": 2},
		},
		{
			name:      "only Chiniisou concealed",
			handCodes: []string{"1m", "1m", "1m", "1m", "2m", "3m", "3m", "4m", "5m", "7m", "8m", "9m", "9m", "9m"},
			handBlocks: []block.Block{
				block.MustTriplet(*tile.MustTileFromCode("1m")),
				block.MustSequence(*tile.MustTileFromCode("1m")),
				block.MustSequence(*tile.MustTileFromCode("3m")),
				block.MustSequence(*tile.MustTileFromCode("7m")),
				block.MustPair(*tile.MustTileFromCode("9m")),
			},
			melds:          nil,
			prevalentWind:  wind.East,
			seatWind:       wind.South,
			doraIndicators: nil,
			riichi:         false,
			wantFu:         40,
			wantHan:        6,
			wantYakus:      map[string]int{"cis": 6},
		},
		{
			name:      "only Chiniisou open",
			handCodes: []string{"1m", "2m", "3m", "3m", "4m", "5m", "7m", "8m", "9m", "9m", "9m"},
			handBlocks: []block.Block{
				block.MustSequence(*tile.MustTileFromCode("1m")),
				block.MustSequence(*tile.MustTileFromCode("3m")),
				block.MustSequence(*tile.MustTileFromCode("7m")),
				block.MustPair(*tile.MustTileFromCode("9m")),
			},
			melds: []meld.Meld{
				meld.MustPon(
					*tile.MustTileFromCode("1m"),
					[2]tile.Tile{*tile.MustTileFromCode("1m"), *tile.MustTileFromCode("1m")},
					*player.MustID(2),
				),
			},
			prevalentWind:  wind.East,
			seatWind:       wind.South,
			doraIndicators: nil,
			riichi:         false,
			wantFu:         30,
			wantHan:        5,
			wantYakus:      map[string]int{"cis": 5},
		},
		{
			name:      "only Honiisou concealed",
			handCodes: []string{"1m", "1m", "1m", "1m", "2m", "3m", "3m", "4m", "5m", "7m", "8m", "9m", "W", "W"},
			handBlocks: []block.Block{
				block.MustTriplet(*tile.MustTileFromCode("1m")),
				block.MustSequence(*tile.MustTileFromCode("1m")),
				block.MustSequence(*tile.MustTileFromCode("3m")),
				block.MustSequence(*tile.MustTileFromCode("7m")),
				block.MustPair(*tile.MustTileFromCode("W")),
			},
			melds:          nil,
			prevalentWind:  wind.East,
			seatWind:       wind.South,
			doraIndicators: nil,
			riichi:         false,
			wantFu:         40,
			wantHan:        3,
			wantYakus:      map[string]int{"his": 3},
		},
		{
			name:      "only Honiisou open",
			handCodes: []string{"1m", "2m", "3m", "3m", "4m", "5m", "7m", "8m", "9m", "W", "W"},
			handBlocks: []block.Block{
				block.MustSequence(*tile.MustTileFromCode("1m")),
				block.MustSequence(*tile.MustTileFromCode("3m")),
				block.MustSequence(*tile.MustTileFromCode("7m")),
				block.MustPair(*tile.MustTileFromCode("W")),
			},
			melds: []meld.Meld{
				meld.MustPon(
					*tile.MustTileFromCode("1m"),
					[2]tile.Tile{*tile.MustTileFromCode("1m"), *tile.MustTileFromCode("1m")},
					*player.MustID(2),
				),
			},
			prevalentWind:  wind.East,
			seatWind:       wind.South,
			doraIndicators: nil,
			riichi:         false,
			wantFu:         30,
			wantHan:        2,
			wantYakus:      map[string]int{"his": 2},
		},
		{
			name:      "Tsuuiisou is considered Honiisou",
			handCodes: []string{"E", "E", "E", "S", "S", "S", "W", "W", "W", "N", "N", "N", "P", "P"},
			handBlocks: []block.Block{
				block.MustTriplet(*tile.MustTileFromCode("E")),
				block.MustTriplet(*tile.MustTileFromCode("S")),
				block.MustTriplet(*tile.MustTileFromCode("W")),
				block.MustTriplet(*tile.MustTileFromCode("N")),
				block.MustPair(*tile.MustTileFromCode("P")),
			},
			melds:          nil,
			prevalentWind:  wind.East,
			seatWind:       wind.South,
			doraIndicators: nil,
			riichi:         false,
			wantFu:         40,
			wantHan:        9,
			wantYakus:      map[string]int{"cty": 2, "ykh": 2, "tth": 2, "his": 3},
		},
		{
			name:      "Riichi Tanyao Pinfu Iipeikou Sanshoku doujun",
			handCodes: []string{"2m", "2m", "3m", "3m", "4m", "4m", "2p", "3p", "4p", "2s", "3s", "4s", "8s", "8s"},
			handBlocks: []block.Block{
				block.MustSequence(*tile.MustTileFromCode("2m")),
				block.MustSequence(*tile.MustTileFromCode("2m")),
				block.MustSequence(*tile.MustTileFromCode("2p")),
				block.MustSequence(*tile.MustTileFromCode("2s")),
				block.MustPair(*tile.MustTileFromCode("8s")),
			},
			melds:          nil,
			prevalentWind:  wind.East,
			seatWind:       wind.South,
			doraIndicators: nil,
			riichi:         true,
			wantFu:         30,
			wantHan:        6,
			wantYakus:      map[string]int{"reach": 1, "tyc": 1, "pf": 1, "ipk": 1, "ssj": 2},
		},
		{
			name:      "Riichi Dora 5",
			handCodes: []string{"1m", "1m", "1m", "2p", "3p", "4p", "3s", "4s", "5s", "6s", "6s", "6s", "9s", "9s"},
			handBlocks: []block.Block{
				block.MustTriplet(*tile.MustTileFromCode("1m")),
				block.MustSequence(*tile.MustTileFromCode("2p")),
				block.MustSequence(*tile.MustTileFromCode("3s")),
				block.MustTriplet(*tile.MustTileFromCode("6s")),
				block.MustPair(*tile.MustTileFromCode("9s")),
			},
			melds:          nil,
			prevalentWind:  wind.East,
			seatWind:       wind.South,
			doraIndicators: []tile.Tile{*tile.MustTileFromCode("8s"), *tile.MustTileFromCode("8s"), *tile.MustTileFromCode("1p")},
			riichi:         true,
			wantFu:         40,
			wantHan:        6,
			wantYakus:      map[string]int{"reach": 1, "dr": 5},
		},
		{
			name:      "open Tanyao Dora 3 Red 2",
			handCodes: []string{"2m", "2m", "2m", "3m", "4m", "5mr", "6s", "6s", "6s", "8s", "8s"},
			handBlocks: []block.Block{
				block.MustTriplet(*tile.MustTileFromCode("2m")),
				block.MustSequence(*tile.MustTileFromCode("3m")),
				block.MustTriplet(*tile.MustTileFromCode("6s")),
				block.MustPair(*tile.MustTileFromCode("8s")),
			},
			melds: []meld.Meld{
				meld.MustPon(
					*tile.MustTileFromCode("5p"),
					[2]tile.Tile{*tile.MustTileFromCode("5p"), *tile.MustTileFromCode("5pr")},
					*player.MustID(2),
				),
			},
			prevalentWind:  wind.East,
			seatWind:       wind.South,
			doraIndicators: []tile.Tile{*tile.MustTileFromCode("4p")},
			riichi:         false,
			wantFu:         30,
			wantHan:        6,
			wantYakus:      map[string]int{"tyc": 1, "dr": 3, "adr": 2},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			hand := hand.CodesToHand(tt.handCodes)
			fu, han, yakus := service.CalculateFuHan(hand, tt.handBlocks, tt.melds, tt.prevalentWind, tt.seatWind, tt.doraIndicators, tt.riichi)
			if tt.wantFu != fu {
				t.Errorf("CalculateFuHan() = %v, want %v", fu, tt.wantFu)
			}
			if tt.wantHan != han {
				t.Errorf("CalculateFuHan() = %v, want %v", han, tt.wantHan)
			}
			if !reflect.DeepEqual(tt.wantYakus, yakus) {
				t.Errorf("CalculateFuHan() = %v, want %v", yakus, tt.wantYakus)
			}
		})
	}
}

func TestHas1Han(t *testing.T) {
	tests := []struct {
		name          string
		handCodes     []string
		melds         []meld.Meld
		winningTile   *tile.Tile
		prevalentWind wind.Wind
		seatWind      wind.Wind
		tsumo         bool
		riichi        bool
		event         service.WinEvent
		want          bool
	}{
		{
			name:          "chiitoitsu",
			handCodes:     []string{"1m", "1m", "8m", "8m", "2p", "8p", "8p", "5s", "5s", "E", "E", "C", "C"},
			melds:         nil,
			winningTile:   tile.MustTileFromCode("2p"),
			prevalentWind: wind.East,
			seatWind:      wind.South,
			tsumo:         false,
			riichi:        false,
			event:         service.NoEvent,
			want:          true,
		},
		{
			name:          "kokushimusou",
			handCodes:     []string{"1m", "9m", "1p", "9p", "1s", "9s", "E", "S", "W", "N", "P", "F", "C"},
			melds:         nil,
			winningTile:   tile.MustTileFromCode("C"),
			prevalentWind: wind.East,
			seatWind:      wind.South,
			tsumo:         false,
			riichi:        false,
			event:         service.NoEvent,
			want:          true,
		},
		{
			name:          "no Yaku",
			handCodes:     []string{"1m", "1m", "1m", "2p", "3p", "4p", "3s", "4s", "5s", "6s", "6s", "6s", "9s"},
			melds:         nil,
			winningTile:   tile.MustTileFromCode("9s"),
			prevalentWind: wind.East,
			seatWind:      wind.South,
			tsumo:         false,
			riichi:        false,
			event:         service.NoEvent,
			want:          false,
		},
		{
			name:          "only Riichi",
			handCodes:     []string{"1m", "1m", "1m", "2p", "3p", "4p", "3s", "4s", "5s", "6s", "6s", "6s", "9s"},
			melds:         nil,
			winningTile:   tile.MustTileFromCode("9s"),
			prevalentWind: wind.East,
			seatWind:      wind.South,
			tsumo:         false,
			riichi:        true,
			event:         service.NoEvent,
			want:          true,
		},
		{
			name:          "only Menzenchin tsumohou",
			handCodes:     []string{"1m", "1m", "1m", "2p", "3p", "4p", "3s", "4s", "5s", "6s", "6s", "6s", "9s"},
			melds:         nil,
			winningTile:   tile.MustTileFromCode("9s"),
			prevalentWind: wind.East,
			seatWind:      wind.South,
			tsumo:         true,
			riichi:        false,
			event:         service.NoEvent,
			want:          true,
		},
		{
			name:      "open tsumohou without yaku",
			handCodes: []string{"2p", "3p", "4p", "3s", "4s", "5s", "6s", "6s", "6s", "9s"},
			melds: []meld.Meld{
				meld.MustPon(
					*tile.MustTileFromCode("1m"),
					[2]tile.Tile{*tile.MustTileFromCode("1m"), *tile.MustTileFromCode("1m")},
					*player.MustID(2),
				),
			},
			winningTile:   tile.MustTileFromCode("9s"),
			prevalentWind: wind.East,
			seatWind:      wind.South,
			tsumo:         true,
			riichi:        false,
			event:         service.NoEvent,
			want:          false,
		},
		{
			name:      "Robbing a kan",
			handCodes: []string{"3p", "4p", "3s", "4s", "5s", "6s", "6s", "6s", "9s", "9s"},
			melds: []meld.Meld{
				meld.MustPon(
					*tile.MustTileFromCode("1m"),
					[2]tile.Tile{*tile.MustTileFromCode("1m"), *tile.MustTileFromCode("1m")},
					*player.MustID(2),
				),
			},
			winningTile:   tile.MustTileFromCode("2p"),
			prevalentWind: wind.East,
			seatWind:      wind.South,
			tsumo:         false,
			riichi:        false,
			event:         service.RobbingAKan,
			want:          true,
		},
		{
			name:          "only Tanyao",
			handCodes:     []string{"2m", "2m", "2m", "2p", "3p", "4p", "3s", "4s", "5s", "6s", "6s", "6s", "8s"},
			melds:         nil,
			winningTile:   tile.MustTileFromCode("8s"),
			prevalentWind: wind.East,
			seatWind:      wind.South,
			tsumo:         false,
			riichi:        false,
			event:         service.NoEvent,
			want:          true,
		},
		{
			name:          "only Iipeikou",
			handCodes:     []string{"1m", "1m", "2p", "3p", "4p", "3s", "4s", "5s", "3s", "4s", "5s", "9s", "9s"},
			melds:         nil,
			winningTile:   tile.MustTileFromCode("1m"),
			prevalentWind: wind.East,
			seatWind:      wind.South,
			tsumo:         false,
			riichi:        false,
			event:         service.NoEvent,
			want:          true,
		},
		{
			name:          "only Pinfu",
			handCodes:     []string{"2m", "3m", "2p", "3p", "4p", "3s", "4s", "5s", "6s", "7s", "8s", "W", "W"},
			melds:         nil,
			winningTile:   tile.MustTileFromCode("1m"),
			prevalentWind: wind.East,
			seatWind:      wind.South,
			tsumo:         false,
			riichi:        false,
			event:         service.NoEvent,
			want:          true,
		},
		{
			name:          "not Pinfu: edge wait",
			handCodes:     []string{"1m", "2m", "2p", "3p", "4p", "3s", "4s", "5s", "6s", "7s", "8s", "W", "W"},
			melds:         nil,
			winningTile:   tile.MustTileFromCode("3m"),
			prevalentWind: wind.East,
			seatWind:      wind.South,
			tsumo:         false,
			riichi:        false,
			event:         service.NoEvent,
			want:          false,
		},
		{
			name:      "only prevalentWind",
			handCodes: []string{"2p", "3p", "8s", "8s", "8s", "N", "N"},
			melds: []meld.Meld{
				meld.MustPon(
					*tile.MustTileFromCode("1m"),
					[2]tile.Tile{*tile.MustTileFromCode("1m"), *tile.MustTileFromCode("1m")},
					*player.MustID(2),
				),
				meld.MustPon(
					*tile.MustTileFromCode("E"),
					[2]tile.Tile{*tile.MustTileFromCode("E"), *tile.MustTileFromCode("E")},
					*player.MustID(2),
				),
			},
			winningTile:   tile.MustTileFromCode("1p"),
			prevalentWind: wind.East,
			seatWind:      wind.South,
			tsumo:         false,
			riichi:        false,
			event:         service.NoEvent,
			want:          true,
		},
		{
			name:      "only Chantaiyao open",
			handCodes: []string{"1p", "2p", "3p", "9s", "9s", "9s", "N"},
			melds: []meld.Meld{
				meld.MustPon(
					*tile.MustTileFromCode("1m"),
					[2]tile.Tile{*tile.MustTileFromCode("1m"), *tile.MustTileFromCode("1m")},
					*player.MustID(2),
				),
				meld.MustChii(
					*tile.MustTileFromCode("7s"),
					[2]tile.Tile{*tile.MustTileFromCode("8s"), *tile.MustTileFromCode("9s")},
					*player.MustID(2),
				),
			},
			winningTile:   tile.MustTileFromCode("N"),
			prevalentWind: wind.East,
			seatWind:      wind.South,
			tsumo:         false,
			riichi:        false,
			event:         service.NoEvent,
			want:          true,
		},
		{
			name:          "only Sanshoku doujun concealed",
			handCodes:     []string{"1m", "1m", "1m", "2m", "3m", "1p", "2p", "3p", "1s", "2s", "3s", "8s", "8s"},
			melds:         nil,
			winningTile:   tile.MustTileFromCode("1m"),
			prevalentWind: wind.East,
			seatWind:      wind.South,
			tsumo:         false,
			riichi:        false,
			event:         service.NoEvent,
			want:          true,
		},
		{
			name:          "only Ikki tsuukan concealed",
			handCodes:     []string{"1m", "1m", "1m", "1p", "2p", "3p", "4p", "5p", "6p", "8p", "9p", "8s", "8s"},
			melds:         nil,
			winningTile:   tile.MustTileFromCode("7p"),
			prevalentWind: wind.East,
			seatWind:      wind.South,
			tsumo:         false,
			riichi:        false,
			event:         service.NoEvent,
			want:          true,
		},
		{
			name:      "only Toitoihou",
			handCodes: []string{"2p", "2p", "6p", "6p", "N", "N", "N"},
			melds: []meld.Meld{
				meld.MustPon(
					*tile.MustTileFromCode("2m"),
					[2]tile.Tile{*tile.MustTileFromCode("2m"), *tile.MustTileFromCode("2m")},
					*player.MustID(2),
				),
				meld.MustCalledKan(
					*tile.MustTileFromCode("1m"),
					[3]tile.Tile{*tile.MustTileFromCode("1m"), *tile.MustTileFromCode("1m"), *tile.MustTileFromCode("1m")},
					*player.MustID(2),
				),
			},
			winningTile:   tile.MustTileFromCode("2p"),
			prevalentWind: wind.East,
			seatWind:      wind.South,
			tsumo:         false,
			riichi:        false,
			event:         service.NoEvent,
			want:          true,
		},
		{
			name:      "only Sanankou",
			handCodes: []string{"2p", "2p", "6p", "6p", "N", "N", "N"},
			melds: []meld.Meld{
				meld.MustChii(
					*tile.MustTileFromCode("1m"),
					[2]tile.Tile{*tile.MustTileFromCode("2m"), *tile.MustTileFromCode("3m")},
					*player.MustID(2),
				),
				meld.MustConcealedKan(
					[4]tile.Tile{*tile.MustTileFromCode("9s"), *tile.MustTileFromCode("9s"), *tile.MustTileFromCode("9s"), *tile.MustTileFromCode("9s")},
				),
			},
			winningTile:   tile.MustTileFromCode("2p"),
			prevalentWind: wind.East,
			seatWind:      wind.South,
			tsumo:         true,
			riichi:        false,
			event:         service.NoEvent,
			want:          true,
		},
		{
			name:      "not Sanankou: 2 ankou",
			handCodes: []string{"2p", "2p", "6p", "6p", "N", "N", "N"},
			melds: []meld.Meld{
				meld.MustChii(
					*tile.MustTileFromCode("1m"),
					[2]tile.Tile{*tile.MustTileFromCode("2m"), *tile.MustTileFromCode("3m")},
					*player.MustID(2),
				),
				meld.MustConcealedKan(
					[4]tile.Tile{*tile.MustTileFromCode("9s"), *tile.MustTileFromCode("9s"), *tile.MustTileFromCode("9s"), *tile.MustTileFromCode("9s")},
				),
			},
			winningTile:   tile.MustTileFromCode("2p"),
			prevalentWind: wind.East,
			seatWind:      wind.South,
			tsumo:         false,
			riichi:        false,
			event:         service.NoEvent,
			want:          false,
		},
		{
			name:      "only Sanshoku doukou",
			handCodes: []string{"2p", "4p", "7s", "7s", "7s", "N", "N"},
			melds: []meld.Meld{
				meld.MustPon(
					*tile.MustTileFromCode("7m"),
					[2]tile.Tile{*tile.MustTileFromCode("7m"), *tile.MustTileFromCode("7m")},
					*player.MustID(2),
				),
				meld.MustPon(
					*tile.MustTileFromCode("7p"),
					[2]tile.Tile{*tile.MustTileFromCode("7p"), *tile.MustTileFromCode("7p")},
					*player.MustID(2),
				),
			},
			winningTile:   tile.MustTileFromCode("3p"),
			prevalentWind: wind.East,
			seatWind:      wind.South,
			tsumo:         false,
			riichi:        false,
			event:         service.NoEvent,
			want:          true,
		},
		{
			name:      "not Sanshoku doukou",
			handCodes: []string{"2p", "4p", "7s", "7s", "N", "N", "N"},
			melds: []meld.Meld{
				meld.MustPon(
					*tile.MustTileFromCode("7m"),
					[2]tile.Tile{*tile.MustTileFromCode("7m"), *tile.MustTileFromCode("7m")},
					*player.MustID(2),
				),
				meld.MustPon(
					*tile.MustTileFromCode("7p"),
					[2]tile.Tile{*tile.MustTileFromCode("7p"), *tile.MustTileFromCode("7p")},
					*player.MustID(2),
				),
			},
			winningTile:   tile.MustTileFromCode("3p"),
			prevalentWind: wind.East,
			seatWind:      wind.South,
			tsumo:         false,
			riichi:        false,
			event:         service.NoEvent,
			want:          false,
		},
		{
			name:      "only Sankantsu",
			handCodes: []string{"2p", "4p", "N", "N"},
			melds: []meld.Meld{
				meld.MustCalledKan(
					*tile.MustTileFromCode("2m"),
					[3]tile.Tile{*tile.MustTileFromCode("2m"), *tile.MustTileFromCode("2m"), *tile.MustTileFromCode("2m")},
					*player.MustID(2),
				),
				meld.MustConcealedKan(
					[4]tile.Tile{*tile.MustTileFromCode("6p"), *tile.MustTileFromCode("6p"), *tile.MustTileFromCode("6p"), *tile.MustTileFromCode("6p")},
				),
				meld.MustPromotedKan(
					*tile.MustTileFromCode("7p"),
					[2]tile.Tile{*tile.MustTileFromCode("7p"), *tile.MustTileFromCode("7p")},
					*tile.MustTileFromCode("7p"),
					*player.MustID(2),
				),
			},
			winningTile:   tile.MustTileFromCode("3p"),
			prevalentWind: wind.East,
			seatWind:      wind.South,
			tsumo:         false,
			riichi:        false,
			event:         service.NoEvent,
			want:          true,
		},
		{
			name:          "only Honiisou concealed",
			handCodes:     []string{"1m", "1m", "1m", "2m", "3m", "3m", "4m", "5m", "7m", "8m", "9m", "W", "W"},
			melds:         nil,
			winningTile:   tile.MustTileFromCode("1m"),
			prevalentWind: wind.East,
			seatWind:      wind.South,
			tsumo:         false,
			riichi:        false,
			event:         service.NoEvent,
			want:          true,
		},
		{
			name:          "only Chiniisou concealed",
			handCodes:     []string{"1m", "1m", "1m", "2m", "3m", "3m", "4m", "5m", "7m", "8m", "9m", "9m", "9m"},
			melds:         nil,
			winningTile:   tile.MustTileFromCode("1m"),
			prevalentWind: wind.East,
			seatWind:      wind.South,
			tsumo:         false,
			riichi:        false,
			event:         service.NoEvent,
			want:          true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			hand := hand.CodesToHand(tt.handCodes)
			got := service.Has1Han(hand, tt.melds, tt.winningTile, tt.prevalentWind, tt.seatWind, tt.tsumo, tt.riichi, tt.event)
			if got != tt.want {
				t.Errorf("Has1Han() = %v, want %v", got, tt.want)
			}
		})
	}
}
